### ISSUE TITLE
Marky crashes... on OSX

### ISSUE THREAD

**Issue by kitofr** [neochrome/marky#2]
```
λ marky --version                                                                                                                                                       
0.3.2
λ marky --style github README.md

λ
```

Node window appears (in tray) and then disappears.

**Comment by neochrome** [comment]
Strange. I'll see if I can push a version that can give some more feedback.

**Comment by neochrome** [comment]
Ok, new version (v0.4.0) out with support for some debugging.
Try this: `$ marky -vv -s github README.md`.
Also, `--dev-tools` may be used to enable the standard chromium dev tools. Not so useful if it not even starts, but nevertheless.

**Comment by neochrome** [comment]
I think this should work by now (31100532a882ac4f734b1f10e697af1607bcdf44) - I have switched to electron and use no fancy file watcher anymore, just plain ol'nodejs

**Comment by kitofr** [comment]
ok sweet. haven't tried in a while...
